version: "3.8"

services:
  umbrella-backend:
    image: spvav/umbrella-backend:latest
    build: ./backend
    ports:
      - 8080:8080

  umbrella-frontend:
    image: spvav/umbrella-frontend:latest
    build: ./frontend
    ports:
      - 4200:4200
